---
# Source: spring-boot-app-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-ui
spec:
  selector:
    matchLabels:
      app: spring-boot-ui
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-ui
    spec:
      containers:
        - name: spring-boot-app-ui
          image: "mtarng/jackson-ui:v1.0"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
            
          ports:
          - containerPort: 8080
            name: ui
          

---
# Add routing rules for the existing Gateway included with Istio
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jackson-route-rules
spec:
  # https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
  gateways: # The default `mesh` value for when left blank is doesn't seem to propigate the rule properly. For now, always use a list of FQDN gateways
    - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local # must be FQDN if VirtualService in different NS than Gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 8080
            host: jackson-api.default.svc.cluster.local
    - route: # This rule will pickup all other requests because it doesn't have a `match`
        - destination:
            port:
              number: 8080
            host: jackson-ui.default.svc.cluster.local

